fcm:
  certification-path: firebase/gloddy-firebase-adminsdk.json

amazon:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com/
  aws:
    accessKey: AKIA25TM4B3T5ZQYGJ7O
    secretKey: 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
    region: ap-northeast-2
